
server.port=8080

# User Service
spring.cloud.gateway.server.webflux.routes[0].id=userservice
spring.cloud.gateway.server.webflux.routes[0].uri=lb://userservice
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/users/**

# Product Service
spring.cloud.gateway.server.webflux.routes[1].id=productservice
spring.cloud.gateway.server.webflux.routes[1].uri=lb://productservice
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/products/**

# Order Service
spring.cloud.gateway.server.webflux.routes[2].id=orderservice
spring.cloud.gateway.server.webflux.routes[2].uri=lb://orderservice
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/orders/**

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Logging
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web.reactive=DEBUG
