server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5432/mobile_notification_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
