spring.application.name=config-server
server.port=8887


# GitHub repository containing centralized configuration
spring.cloud.config.server.git.uri=https://github.com/krishna19-b/Mobile-Backend-Microservices.git

# Folder containing the centralized properties files
spring.cloud.config.server.git.search-paths=config-repo

# Branch containing the configuration
spring.cloud.config.server.git.default-label=main

# Clone the repository during startup
spring.cloud.config.server.git.clone-on-start=true